export const INCREMENT = 'increase'
export const DECREMENT = 'decrease'
export const DELETEBOOK = 'deleteBook'
export const ADDBOOK = 'addBook'
export const BEGIN_GET_POSTS = 'beginGetPosts'
export const GET_USERS = 'getUsers'
export const GET_ERROR = 'getError'